apiVersion: apps/v1
kind: Deployment
metadata:
  name: cockroachdb
  namespace: distribuidas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cockroachdb
  template:
    metadata:
      labels:
        app: cockroachdb
    spec:
      containers:
        - name: cockroachdb
          image: cockroachdb/cockroach:latest
          command: ["cockroach", "start-single-node", "--insecure", "--advertise-addr=cockroachdb"]
          ports:
            - containerPort: 26257
            - containerPort: 8080
          volumeMounts:
            - name: cockroach-data
              mountPath: /cockroach/cockroach-data
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: cockroach-data
          persistentVolumeClaim:
            claimName: cockroach-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cockroach-pvc
  namespace: distribuidas
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-service
  namespace: distribuidas
spec:
  type: ClusterIP
  selector:
    app: cockroachdb
  ports:
    - name: grpc
      port: 26257
      targetPort: 26257
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-nodeport
  namespace: distribuidas
spec:
  type: NodePort
  selector:
    app: cockroachdb
  ports:
    - name: grpc
      port: 26257
      targetPort: 26257
      nodePort: 30257
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
