server:
  port: ${SERVER_PORT:8000}

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: servicio-auth
          uri: lb://servicio-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: servicio-publicaciones
          uri: lb://ms-publish
          predicates:
            - Path=/publicaciones/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter

        - id: servicio-catalogo
          uri: lb://ms-catalogo
          predicates:
            - Path=/catalogo/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter

        - id: servicio-notificaciones
          uri: lb://notificaciones
          predicates:
            - Path=/notificaciones/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.allpasoft.msapigateway: DEBUG
    org.springframework.web.cors: DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server.distribuidas.svc.cluster.local:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: gateway,health
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET:una_clave_muy_segura_1234567890123456}

