apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-auth
  namespace: distribuidas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicio-auth
  template:
    metadata:
      labels:
        app: servicio-auth
    spec:
      containers:
        - name: servicio-auth
          image: authservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: eureka-config
                  key: EUREKA_URL
            - name: DATABASE_URL
              value: "jdbc:postgresql://cockroachdb-service.distribuidas.svc.cluster.local:26257/db-auth?user=root&password="
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: cockroachdb-config
                  key: COCKROACH_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: cockroachdb-config
                  key: COCKROACH_PASSWORD
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret
            - name: JWT_EXPIRATION
              value: "3600000"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 15
