apiVersion: v1
kind: Service
metadata:
  name: servicio-auth
  namespace: distribuidas
spec:
  type: ClusterIP
  selector:
    app: servicio-auth
  ports:
    - name: http
      port: 8080
      targetPort: 8080
