server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: servicio-auth

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://cockroachdb-service.distribuidas.svc.cluster.local:26257/db-auth?user=root&password=}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:}
  jwt:
    secret: ${JWT_SECRET:una_clave_muy_segura_1234567890123456}
    expiration: ${JWT_EXPIRATION:3600000}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq-service.distribuidas.svc.cluster.local}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server.distribuidas.svc.cluster.local:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.allpasoft.authservice: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
