apiVersion: v1
kind: Service
metadata:
  name: notificaciones
  namespace: distribuidas
spec:
  type: ClusterIP
  selector:
    app: notificaciones
  ports:
    - name: http
      port: 8080
      targetPort: 8080
